Update to hashbrown 0.9
CAD97/sorbus pull request #72
Opened 2020-09-03 22:46 UTC by mbrubeck

The behavior of `drain_filter` has changed in this release:

https://github.com/rust-lang/hashbrown/issues/186

2020-09-03 23:51 UTC, CAD97 requested changes
You can tell I wasn't super comfortable with the parity previously implemented, thus leaving the clarifying comment.

The first half of the clarifying comment is also made incorrect by the change/fix, so it also needs to be changed.

I think were `drain_filter` to have been stable with these semantics originally, I wouldn't have felt the need to add the clarifying comment in the first place. I probably would have still added the comment had it been stable with `retain`'s parity.

Until `drain_filter` is stabilized, I think the comment is definitely still valuable; once the method is stabilized, the comment may be judged unnecessary.

You can fix the rest of the comment and I'll merge this, or I'll get around to doing as such the next time I get some time to work on pushing this to be ready to integrate into rowan/r-a.

2020-09-03 23:51 UTC, CAD97 commented on src/green/builder.rs
>          // NB: `drain_filter` is `retain` but with an iterator of the removed elements.
This line of the comment is wrong now that the parity is flipped to be determining the elements drained, not the elements retained.

I think the correct analogue would now be

```suggestion
        // NB: `drain_filter` is `iter().filter` but also removing the elements chosen.
```

2020-09-04 00:21 UTC, mbrubeck commented
Applied your comment fix.

2020-09-04 05:34 UTC, CAD97 commented
bors: r+

2020-09-04 05:42 UTC, merged